[workspace]
resolver = "2"
members = [ 
    "cli",
    "compiler",
    "compiler_web",
    "xtask", 
    "wasm_exec",
]

[workspace.metadata.bin]
cargo-nextest = { version = "0.9.72" }
wasm-pack = { version = "0.13.0" }
