[package]
name = "kedi"
version = "0.1.0"
edition = "2021"
default-run = "kedi"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
kedi-lang = { path = "../compiler" }
miette = { version = "7.2.0", features = ["fancy"] }
patharg = "0.4.0"
wasm-exec = { path = "../wasm_exec" }
