[package]
name = "kedi-lang"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bimap = "0.6.3"
indices = "0.3.1"
lazy_static = "1.4.0"
miette = "7.2.0"
pest = "2.7.5"
pest-ast = "0.3.4"
pest_derive = "2.7.5"
pretty = "0.12.3"
source-map = "0.15.0"
thiserror = "1.0.61"
ustr = "1.0.0"
wasm-encoder = "0.209.1"
wasm-opt = "0.116.1"
wasmprinter = "0.209.1"
wast = "209.0.1"

[dev-dependencies]
test-case = "3.3.1"
test_each_file = "0.3.2"
wasmparser = "0.210.0"
wasmtime = "21.0.1"
