[package]
name = "kedi-lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bimap = "0.6.3"
lazy_static = "1.4.0"
nom = "7.1.3"
pest = "2.7.5"
pest-ast = "0.3.4"
pest_derive = "2.7.5"
pretty = "0.12.3"
wasm-encoder = "0.209.1"
wasmprinter = "0.209.1"
wast = "209.0.1"
