name: Deploy website

on:
  push:
    branches: [$default-branch]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # Install toolchain
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    # Build Rust component
    - run: cargo xtask build-website

    # Build website
    - run: npm run build
      working-directory: website/

    # Deploy website
    - uses: actions/upload-pages-artifact@v3
      with:
        path: website/dist
        retention-days: 15
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4